## CAMADA BRONZE INGESTÃO DE DADOS

In [37]:
import duckdb
import pandas as pd
import os
from datetime import datetime

In [45]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [39]:
#arquivo = 'z0019_1.csv'
arquivo = 'z0019_2.csv'
data_ingestao = datetime.now()
#criação de dataframe com pandas
df = pd.read_csv(f'../landing/{arquivo}', sep=';')

#criação de colunas no dataframe para visualização
df['nome_arquivo'] = arquivo
df['data_ingestao'] = data_ingestao
df.head()

   NATBR    MAKTX WERKS  MAINS  LABST nome_arquivo              data_ingestao
0  10004    SERRA  BT50    100    200  z0019_2.csv 2026-10-02 01:14:34.792583
1  10005  MARTELO  BT50    100    100  z0019_2.csv 2026-10-02 01:14:34.792583
2  10003    PREGO  BT10    100     60  z0019_2.csv 2026-10-02 01:14:34.792583

In [ ]:
con.execute("""
    CREATE TABLE IF NOT EXISTS bronze_z0019 (
        NATBR VARCHAR,
        MAKTX VARCHAR,
        WERKS VARCHAR,
        MAINS VARCHAR,
        LABST VARCHAR,
        nome_arquivo VARCHAR,
        data_ingestao TIMESTAMP
    )
""")

In [ ]:
con.execute("INSERT INTO bronze_z0019 SELECT * FROM df")

In [46]:
resultado = con.execute("SELECT * FROM bronze_z0019").fetch_df()
resultado.head(6)

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-10-02 00:49:45.337043
1  10002   MARTELO  BT50   100  1500  z0019_1.csv 2026-10-02 00:49:45.337043
2  10003     PREGO  BT10   100    50  z0019_1.csv 2026-10-02 00:49:45.337043
3  10004     SERRA  BT50   100   200  z0019_2.csv 2026-10-02 01:01:50.176410
4  10005   MARTELO  BT50   100   100  z0019_2.csv 2026-10-02 01:01:50.176410
5  10003     PREGO  BT10   100    60  z0019_2.csv 2026-10-02 01:01:50.176410

In [47]:
con.close()